[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
ahash = "0.7.6"
sorted-vec = "0.8.1"
bitvec = "1"
itertools = "0.10.5"
num-integer = "0.1"
num = "0.4.0"
